vim.cmd.colorscheme("catppuccin")
-- vim.cmd.colorscheme("rose-pine")
-- vim.cmd.colorscheme("tokyodark")
-- vim.cmd.colorscheme("github_dark")
-- vim.cmd.colorscheme("github_dark_high_contrast")
-- vim.cmd.colorscheme("tokyonight-night")
-- vim.cmd.colorscheme("tokyonight")
-- vim.cmd.colorscheme("github_dark_colorblind")

-- vim.cmd.colorscheme("synthweave")
-- vim.cmd.colorscheme("citruszest")
